### ISSUE TITLE
Panic over AppleACPIPlatform with 10.13 when the same print was fine on 10.12

### ISSUE THREAD

**Issue by noone321234** [RehabMan/OS-X-Clover-Laptop-Config#29]
In the last few days I've found myself trying to debug this issue over and over again. The installer for 10.13 panics after a few errors (before printing all of them) that looks like this:

` (AppleACPIPlatform)
ACPI Error: No handler for Region [EC81]  [EmbeddedControl] (20140828/evregion-f9)
ACPI Error: No handler for Region [EC81] (20140828/evregion-f9)
ACPI Error: Region EmbeddedControl (ID=3) has no handler (20140828/exfldio-187)
ACPI Error: Region EmbeddedControl (ID=3) has no handler (20140828/exfldio-187)
ACPI Error: Method parse/execution failed  [\_SB_.PCI0.PEG0.GFX0.SGOF]  , AE_NOT_EXIST
ACPI Error: Method parse/execution failed  [\_SB_.PCI0.PEG0.GFX0.SGOF]  , AE_NOT_EXIST
ACPI Error: Method parse/execution failed [\_SB_.PCI0.PEG0.GFX0._OFF] , AE_NOT_EXIST
ACPI Error: Method parse/execution failed  [\_SB_.PCI0.PEG0.GFX0._OFF] , AE_NOT_EXIST
ACPI Error: Method parse/execution failed [\_SB_.PCI0.PEG0.GFX0._INI], AE_NOT_EXIST
ACPI Error: Method parse/execution failed [\_SB_.PCI0.PEG0.GFX0._INI], AE_NOT_EXIST`

After a lot of research and documentation effort, I've understood that the issue probably is still related to the isprint function bugged inside AppleACPIPlatform and the table indexes that goes negatives, but the panics (from the print screen they seems multiples) are so fast that trying to get anything useful from them is quite hard. Anyway, removing the patch named #graphics_REG-disable.txt fixes the error above and the installer now boots happily. Besides closing and opening once the laptop after boot to trigger the code, there is any other way besides _REG EC function to trigger it on boot? I've already tried to apply it on _INI, but the EC is still not initialised and doesn't do nothing unfortunately.

I'm not sure that this is the right place to post it, but it seems to be a starting place.

**Comment by RehabMan** [comment]
Not related to isprint.
The "No handler for Region ... [EmbeddedControl]" is because of some code your ACPI files accessing an EC region before _REG has been called in such a way as to make the EC region available (read the ACPI spec for details).

From the trace, it looks like you're calling _OFF from _INI in an effort to turn off a discrete graphics device, that that _OFF path (looks like SGOF) is accessing the EC.

All such code must be moved to _REG.
See guide:
https://www.tonymacx86.com/threads/guide-disabling-discrete-graphics-in-dual-gpu-laptops.163772/
